TRTLLM_GEMM_ALLREDUCE_WORKSPACE_SIZE:137494528
TLLM_NUMA_AWARE_WORKER_AFFINITY:1
CUDA_SCALE_LAUNCH_QUEUES:4x
OMPI_MCA_hwloc_base_binding_policy:none
OMPI_MCA_rmaps_base_inherit:1
TRTLLM_GEMM_ALLREDUCE_FUSION_ENABLED:1
TRTLLM_LLAMA_EAGER_FUSION_DISABLED:1
TRTLLM_DISABLE_NVFP4_LAYERNORM_FUSION:0
