gpt-oss-120b.*.performance_sample_count_override = 6396
gpt-oss-120b.*.accuracy_sample_count_override = 4395
gpt-oss-120b.*.sample_concatenate_permutation = 1

#gpt-oss-120b.Server.target_latency = 0
#gpt-oss-120b.Server.ttft_latency = 3000
#gpt-oss-120b.Server.tpot_latency = 80

gpt-oss-120b.Server.target_qps = 1
gpt-oss-120b.Offline.target_qps = 1


